spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
      routes:
        - id: account-book-service
          uri: lb://ACCOUNT-BOOK-SERVICE
          predicates:
            - Path=/account-book/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:3333/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

auth:
  token:
    secretKey: sadfasdfsafdsadfsadfsafdsafdsafdsafdsafdsafdsafdsafdsafdsafsadfsadfsafdsadfsafdsadf
    accessTokenExpiry: 9900000
    refreshTokenExpiry: 604800000
